### ISSUE TITLE
Spine3.2.01 Support

### ISSUE THREAD

**Issue by ghost** [kiletw/SpineViewerWPF#11]
A support for Ver3.2.01 plz , thx : )
when I load .skel binary file crashed with other version of Spine

**Comment by kiletw** [comment]
Maybe you can upload spine files.
I will check it.

**Comment by Poityu** [comment]
Hello,

Will the sample below do?
[sample.zip](https://github.com/kiletw/SpineViewerWPF/files/5763634/sample.zip)

Pardon my intrusion, it just so happened that my attempt to replay skel animations eventually led me here a moment ago. I am highly confident that this is a *.skel from V 3.2.01, since this number string can be found in multiple *.skel files.

Side note: these were extracted through AssetStudio, the png is 1024x1024, but the spec in the*.atlas says 1511x1511. Resizing the png works, (tested with atlas png unpacking,) hopefully nothing is wrong with the *.skel.

Other options: 
Spine Editor: Trial version does not support version roll back. Locked to V 4.05.
Skeleton Viewer: No compatible version found.
Unity: Runtime spine-unity V 3.2.01 is nowhere to be found (even with WaybackMachine).

**Comment by ghost** [comment]
> Maybe you can upload spine files.
> I will check it.

[b0037s4.zip](https://github.com/kiletw/SpineViewerWPF/files/5763839/b0037s4.zip)
Thx for ur reply, 
there are source files which .png size not match the .atlas format file,but after resizing , also no responese and crash

**Comment by kiletw** [comment]
[#fix](https://github.com/kiletw/SpineViewerWPF/commit/1f774941d6b8c8aab3ec6e31d2e488c6c8ec77ce)

**Comment by Poityu** [comment]
KUDOS IN CAPITALS!🙏

Btw @kiletw, 首頁的
中文說明請看這裡
連結應該是 README_zhTW.md, 
但是現在是 README.zhTW.md,
造成404.

Thanks again!
