### ISSUE TITLE
3.8.85  crashed 

### ISSUE THREAD

**Issue by k330258a** [kiletw/SpineViewerWPF#8]
Hello i tried to use 3.8.85, .skel but crashed help me. Thank you

**Comment by kiletw** [comment]
Please upload spine file.

**Comment by k330258a** [comment]
@kiletw thank you.

**solved**  thank.  ---1113

**Comment by kiletw** [comment]
Where are texture files?

**Comment by k330258a** [comment]
**solved**  thank.  ---1113
@kiletw

**Comment by kiletw** [comment]
Because there is a blank line at the end of the atlas file. The correct atlas file does not have this line.

Before
![image](https://user-images.githubusercontent.com/18109554/98970667-8a6f5f00-2553-11eb-9c74-4dfe2d51561a.png)
After
![image](https://user-images.githubusercontent.com/18109554/98970722-99eea800-2553-11eb-98b1-cf2be11705b6.png)

**Comment by k330258a** [comment]
**In normal use, thank you so much.**
Thanks for your program. 😊😊
